### ISSUE TITLE
Since JDK 11.0.20 the unified agent is failing with : failed to execute Unified Agent scan: Failed to determine UA version

### ISSUE THREAD

**Issue by FrankReisenhofer** [whitesource/unified-agent-distribution#48]
When Using JDK 11.0.20 or higher the unified agent is failing with:

failed to execute Unified Agent scan: Failed to determine UA version: running command 'java' failed: cmd.Run() failed: exit status 1

When checking the stacktrace we found [1].

Then we checked the release notes of JDK 11.0.20. and found that the unified agent manifest file is now just to big.

Could you please check this and provide a manifest file which fulfills the basic requirements of Java JDK 11.0.20.

Thanks for your help.

[2]
https://www.oracle.com/java/technologies/javase/11-0-20-relnotes.html#JDK-8300596

[1]

rror: An unexpected error occurred while trying to open file .\wss-unified-agent.jar
java.io.IOException: Unsupported size: 8577957 for JarEntry META-INF/MANIFEST.MF. Allowed max size: 8000000 bytes
        at java.base/java.util.jar.JarFile.getBytes(JarFile.java:810)
        at java.base/java.util.jar.JarFile.getManifestFromReference(JarFile.java:421)
        at java.base/java.util.jar.JarFile.getManifest(JarFile.java:408)
        at java.base/sun.launcher.LauncherHelper.getMainClassFromJar(LauncherHelper.java:553)
        at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:778)
        at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:686)

**Comment by PhillCli** [comment]
a workaround that worked for us - downgrade java-runtime to `17.0.7`

```yaml
      - name: Setup JDK 
        uses: actions/setup-java@v3
        with:
          java-version: 17.0.7
          distribution: 'temurin'
      - name: WhiteSource scan
        shell: bash
        run: |
          curl -LJ -o wss-unified-agent.jar https://unified-agent.s3.amazonaws.com/wss-unified-agent-23.5.2.1.jar
          echo Unified Agent downloaded successfully
          which java
          java --version
          java -Xdiag -jar wss-unified-agent.jar -c whitesource.config
```
